name: CI

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Get Next Version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
          noVersionBumpBehavior: patch

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      # - name: Test
      #   run: npm run test

      - name: Build
        run: npm run build

      - name: Remove .gitignore from dist
        run: |
          rm dist/.gitignore

      - name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          add: "."
          author_name: ${{ vars.CICD_BOT_NAME }}
          author_email: ${{ vars.CICD_BOT_EMAIL }}
          message: "other: Version ${{ steps.semver.outputs.next }}"
          tag: ${{ steps.semver.outputs.next }}
          push: "--force origin ${{ steps.semver.outputs.nextMajor }}"
