name: CI

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Get Next Version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
          noVersionBumpBehavior: patch

      - name: Checkout
        uses: actions/checkout@v4

      - name: Switch to major branch
        env:
          MAJOR: ${{ steps.semver.outputs.nextMajor }}
        run: |
          # Check if branch is already checked out. If yes, then checkout it, otherwise checkout it as a new local branch.
          if git checkout $MAJOR 2>/dev/null; then
            echo "Branch $MAJOR already checked out"
          else
            echo "Branch $MAJOR not yet checked out - checking out now"
            git checkout -b "$MAJOR"
          fi

      - name: Merge main
        run: |
          git merge main

      - name: Remove dist/.gitignore
        run: |
          rm dist/.gitignore

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      # - name: Test
      #   run: npm run test

      - name: Build
        run: npm run build

      - name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          add: "."
          author_name: ${{ vars.CICD_BOT_NAME }}
          author_email: ${{ vars.CICD_BOT_EMAIL }}
          message: "other: Version ${{ steps.semver.outputs.next }}"
          tag: ${{ steps.semver.outputs.next }}
          push: "--force --set-upstream origin ${{ steps.semver.outputs.nextMajor }}"
